# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
name: 15. Historical Scan Triggers
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Run Details'
        required: false
        default: 'Historical Scan Triggers'
      targetPythonVersion:
        description: 'Target Python version: 3.9 , 3.10, 3.11 ?'
        required: false
        type: string
        default: '3.12'
      runson:
          description: 'Runner OS. e.g: ubuntu-latest, windows-latest or macos-latest'
          required: false
          default: 'ubuntu-latest'
      installtalib:
        description: 'Is TA-Lib install required? (Y/N)'
        required: false
        default: 'N'
      scanOptions:
        description: 'Scan options for historical scans'
        required: false
        default: '--reScanForZeroSize --scanDaysInPast 5 --triggerRemotely --scans -f -s2 0,22,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0" -s4 "0"'

  # schedule:
  # - cron: '30 10 * * 0-6'

jobs:

  Download_Historical_Data:

    runs-on: ${{ inputs.runson || 'ubuntu-latest'}} #ubuntu-latest #windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: actions-data-download

    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.targetPythonVersion  || 3.12 }}

    - name: Restore Dependencies from Windows Cache
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Load Cache for Linux Dependencies
      uses: actions/cache@v4
      if: startsWith(runner.os, 'Linux')
      with:
        path: |
          /usr/include/ta-lib
          /usr/bin/ta-lib-config
          /usr/lib/libta_lib.la
          /usr/lib/libta_lib.a
        key: ${{ runner.os }}-talib
        restore-keys: |
          ${{ runner.os }}-talib
          
    - name: Install TA-Lib for Windows
      if: ${{ inputs.installtalib == 'Y' && startsWith(runner.os, 'Windows') }}
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        cd .github/dependencies/
        if [[ "${{ inputs.targetPythonVersion }}" == "" ]] ;then
          pip3 install ta_lib-0.6.0-cp312-cp312-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.9" ]] ;then
          pip3 install TA_Lib-0.4.19-cp39-cp39-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.11" ]] ;then
          pip3 install TA_Lib-0.4.29-cp311-cp311-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.12" ]] ;then
          pip3 install ta_lib-0.6.0-cp312-cp312-win_amd64.whl
        fi

    - name: Install TA-Lib for Linux
      if: ${{ inputs.installtalib == 'Y' && startsWith(runner.os, 'Linux') }}
      run: |
        cd .github/dependencies/
        pwd
        tar -xzf ta-lib-0.6.4-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd /home/runner/work/PKScreener/PKScreener/
        pip3 install ta-lib

    - name: Setup Python environment for triggers on Ubuntu
      shell: bash
      if: startsWith(runner.os, 'Linux')
      continue-on-error: true
      run: |
        cd .github/dependencies/
        pwd
        tar -xzf ta-lib-0.6.4-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd /home/runner/work/PKScreener/PKScreener/
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        pip3 install ta-lib
        pip3 install .

    - name: Setup Python environment for triggers on Windows
      continue-on-error: true
      if: startsWith(runner.os, 'Windows')
      shell: bash
      run: |
        cd .github/dependencies/
        if [[ "${{ inputs.targetPythonVersion }}" == "" ]] ;then
          pip3 install ta_lib-0.6.0-cp312-cp312-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.9" ]] ;then
          pip3 install TA_Lib-0.4.19-cp39-cp39-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.11" ]] ;then
          pip3 install TA_Lib-0.4.29-cp311-cp311-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.12" ]] ;then
          pip3 install ta_lib-0.6.0-cp312-cp312-win_amd64.whl
        fi
        cd ..
        cd ..
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        pip3 install .
        
    - name: Run Historical Scan on Ubuntu
      shell: bash
      env:
        GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
      continue-on-error: true
      if: startsWith(runner.os, 'Linux')
      # X_1,5,8,11,12,14_6_1-to-10
      run: |
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,2,3,4,5,6,7,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,3,4,5,6,7,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,4,5,6,7,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,5,6,7,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,6,7,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,7,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,8,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,7,9,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,7,8,10" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,7,8,9" -s4 "0"'
        
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,2,3,4,5,6,7,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,3,4,5,6,7,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,4,5,6,7,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,5,6,7,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,6,7,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,7,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,8,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,7,9" -s4 "0"'
        python3 .github/workflows/workflowtriggers.py --reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,7,8" -s4 "0"'
        
        python3 .github/workflows/workflowtriggers.py ${{ inputs.scanOptions  || '--reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,6,7,22,29,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0" -s4 "0"' }}

        python3 .github/workflows/workflowtriggers.py ${{ inputs.scanOptions  || '--reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0,M,Z, -s0 S,M,T,E,U,Z,H,Y,B,G,C,M,D,I,L,X -s1 0,M,Z,2,3,4, -s3 "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16" -s4 "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16"' }}

    - name: Run Historical Scan on Windows
      continue-on-error: true
      if: startsWith(runner.os, 'Windows')
      shell: cmd
      env:
        GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
      run: |
        python3 .github/workflows/workflowtriggers.py ${{ inputs.scanOptions  || '--reScanForZeroSize --scanDaysInPast 250 --triggerRemotely --scans -f -s2 0,22,29,30,31,32,33,34,35,36,37,38,39,40,41,42,50,M,Z -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,P -s1 W,N,E,M,Z,S,0,2,3,4,6,7,9,10,13,15 -s3 "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16" -s4 "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16"' }}
        python3 .github/workflows/workflowtriggers.py ${{ inputs.scanOptions  || '--reScanForZeroSize --scanDaysInPast 3 --triggerRemotely --scans -f -s2 0, -s0 S,T,E,U,Z,F,H,Y,B,G,C,M,D,I,L,X -s1 0,2,3,4, -s3 "0" -s4 "0"' }}

  # Delete_Workflow_Run:
  #   runs-on: ubuntu-latest
  #   needs: [Download_Historical_Data]
  #   name: Delete workflow run
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: main
          
  #     - name: Delete this workflow run
  #       if: startsWith(runner.os, 'Linux')
  #       shell: bash
  #       run: |
  #         gh run list --status success --limit 100 --json databaseId -q '.[].databaseId' | xargs -IID gh api "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" -X DELETE
  #         gh run list --status cancelled --limit 100 --json databaseId -q '.[].databaseId' | xargs -IID gh api "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" -X DELETE
  #         gh run list --status failed --limit 100 --json databaseId -q '.[].databaseId' | xargs -IID gh api "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" -X DELETE
  #         # for id in $(gh run list --limit 100 --jq ".[] | select (.status == \"success\" ) | .databaseId" --json databaseId,status); do gh run delete $id; done
  #         # for id in $(gh run list --limit 100 --jq ".[] | select (.status == \"cancelled\" ) | .databaseId" --json databaseId,status); do gh run delete $id; done
  #         # for id in $(gh run list --limit 100 --jq ".[] | select (.status == \"failure\" ) | .databaseId" --json databaseId,status); do gh run delete $id; done
  #         # Cancel runs queued or in_progress. See https://cli.github.com/manual/gh_run_list
  #         # for id in $(gh run list -w "13. Backtest for Generic" --limit 100 --jq ".[] | select (.status == \"queued\" ) | .databaseId" --json databaseId,status); do gh run cancel $id; done 
  #       env:
  #         GH_TOKEN : ${{secrets.GITHUB_TOKEN}}
